export const WISHLIST_WRITE_REPOSITORY = 'WISHLIST_WRITE_REPOSITORY';
export const WISHLIST_READ_REPOSITORY = 'WISHLIST_READ_REPOSITORY';

export const WISHLIST_DEFAULT_WISHLIST_NAME = 'Favorit';

export const MAX_CACHE_TTL_MS = 1000 * 60 * 15; // 15 minutes
